<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fast_limo</name>
  <version>0.0.0</version>
  <description>The fast_limo package in ROS2</description>

  <maintainer email="oriol.martinez.fite@gmail.com">fetty</maintainer>

  <license>Apache License 3.0</license>

  <!-- Build tools -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <!-- Mejor como buildtool_depend (recomendado por ROS2) -->
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Dependencias del nodo / runtime -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>std_msgs</depend>
  <depend>nano_gicp</depend>
  <depend>kiss_matcher</depend>

  <!-- Runtime para las interfaces generadas -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <exec_depend>ros2launch</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- IMPORTANTE: nivel superior, fuera de <export> -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
