#!/bin/bash
set -e

xhost +local:root

DOCKER_NAME="fastlimo-ros2-container"
DOCKER_IMG="fastlimo-ros2-image:latest"

if [[ $# -eq 0 ]] ; then
  echo "INFO: No arguments provided, container ${DOCKER_NAME} from image ${DOCKER_IMG} will be started"
elif [[ $# -eq 1 ]] ; then
  echo "INFO: Only one argument provided, container $1 from image ${DOCKER_IMG} will be started"
  DOCKER_NAME=$1
else
  DOCKER_NAME=$1
  DOCKER_IMG=$2
fi

XAUTH=/tmp/.docker.xauth
PROJECT_ROOT="$(cd "$(dirname "$0")"; pwd)"

if docker ps -l | grep -q ${DOCKER_NAME}; then
  echo "WARNING: A container named ${DOCKER_NAME} was already created; it will be started"
  docker start -i ${DOCKER_NAME}
else
  docker run -it \
    --name ${DOCKER_NAME} \
    --env="DISPLAY=$DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --env="XAUTHORITY=$XAUTH" \
    --net=host \
    --privileged \
    ${DOCKER_IMG} "$@"
fi

xhost -local:root
echo "Goodbye :)"